### ISSUE TITLE
Support the limited availability difficulty

### ISSUE THREAD

**Issue by tupaschoal** [alexanderepolite/JustDeleteMe-extension#2]
https://github.com/jdm-contrib/jdm/pull/1300 introduced a new "limited availability" difficulty, which the extension needs to support. 

Seems like all it needs is a new icon and a few touches here and there, shouldn't be difficult.

**Comment by AlexanderEpolite** [comment]
Would the difficulty be the string `limited` as returned from the data?  Or would it be something else.

**Comment by tupaschoal** [comment]
On the JSON people will input "limited", but on the website it will be rendered as "limited availability"

**Comment by AlexanderEpolite** [comment]
Added in newest version
